version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/image/bookworm"
      - "/image/trixie"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
